#!/bin/bash

# Install OpenBUGS
# Attempt 1 - FAILED with noe about super user authority
# This approach doesn't work because dpkg requires superuser authority, it seems. See https://github.com/jupyterhub/repo2docker/issues/192
#OpenBUGS install based on https://github.com/mavelli/rocker-bayesian/blob/28cc0a8635ce360161e882a8c8a92c278f2b3ffc/Dockerfile
#wget -nd -P /tmp http://pj.freefaculty.org/Debian/squeeze/amd64/openbugs_3.2.2-1_amd64.deb
#dpkg -i /tmp/openbugs_3.2.2-1_amd64.deb && rm /tmp/openbugs_3.2.2-1_amd64.deb 
# Attempt 2 - FAILED with note '/usr/include/stdio.h:27:10: fatal error: bits/libc-header-start.h: No such file or directory ... 
# ... Makefile:233: recipe for target 'all-recursive' failed'
# based on https://github.com/gshamov/R2jags-image/blob/1f0b9c35a00634f6801c99e3c9dacc04aeb84fa7/Singularity
# Note that even though current Ubuntu version on Binder is 18.04 (check via `cat /etc/issue`), when I changed 15.04 to 18.04, I got dead link 
# and looking at https://pj.freefaculty.org/Ubuntu/ shows that addres is last one
#wget http://pj.freefaculty.org/Ubuntu/15.04/amd64/openbugs/openbugs_3.2.3.orig.tar.gz
#tar xzf openbugs_3.2.3.orig.tar.gz
#cd openbugs-3.2.3
#./configure
#make && make check && make install

# Attempt 3
# based on https://github.com/jsta/openbugs and I added items listed at https://github.com/gshamov/R2jags-image/blob/1f0b9c35a00634f6801c99e3c9dacc04aeb84fa7/Singularity to apt.txt based on http://www.openbugs.net/w/Downloads and 
# that it maughe be consistent with error above of `'/usr/include/stdio.h:27:10: fatal error: bits/libc-header-start.h: No such file or directory`
git clone https://github.com/jsta/openbugs.git
cd openbugs
./configure
make && make check && make install




# From http://www.openbugs.net/w/Downloads
# http://www.openbugs.net/w/OpenBUGS_3_2_3?action=AttachFile&do=get&target=OpenBUGS-3.2.3.tar.gz
